import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  appsSidebar: [
    {
      type: 'doc',
      id: 'apps/index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Marketing',
      link: { type: 'doc', id: 'apps/marketing/index' },
      items: [{ type: 'autogenerated', dirName: 'apps/marketing' }],
    },
    {
      type: 'category',
      label: 'Console',
      link: { type: 'doc', id: 'apps/console/index' },
      items: [{ type: 'autogenerated', dirName: 'apps/console' }],
    },
    {
      type: 'category',
      label: 'Lobby',
      link: { type: 'doc', id: 'apps/lobby/index' },
      items: [{ type: 'autogenerated', dirName: 'apps/lobby' }],
    },
    {
      type: 'category',
      label: 'Super Admin',
      link: { type: 'doc', id: 'apps/super-admin/index' },
      items: [{ type: 'autogenerated', dirName: 'apps/super-admin' }],
    },
  ],

  packagesSidebar: [
    {
      type: 'doc',
      id: 'packages/index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'UI Components',
      link: { type: 'doc', id: 'packages/ui/index' },
      items: [{ type: 'autogenerated', dirName: 'packages/ui' }],
    },
    {
      type: 'category',
      label: 'Authentication',
      link: { type: 'doc', id: 'packages/auth/index' },
      items: [{ type: 'autogenerated', dirName: 'packages/auth' }],
    },
    {
      type: 'category',
      label: 'Database',
      link: { type: 'doc', id: 'packages/db/index' },
      items: [{ type: 'autogenerated', dirName: 'packages/db' }],
    },
    {
      type: 'category',
      label: 'Payments',
      link: { type: 'doc', id: 'packages/payments/index' },
      items: [{ type: 'autogenerated', dirName: 'packages/payments' }],
    },
    {
      type: 'category',
      label: 'Email',
      link: { type: 'doc', id: 'packages/email/index' },
      items: [{ type: 'autogenerated', dirName: 'packages/email' }],
    },
    {
      type: 'category',
      label: 'Logger',
      link: { type: 'doc', id: 'packages/logger/index' },
      items: [{ type: 'autogenerated', dirName: 'packages/logger' }],
    },
    {
      type: 'category',
      label: 'Storage',
      link: { type: 'doc', id: 'packages/storage/index' },
      items: [{ type: 'autogenerated', dirName: 'packages/storage' }],
    },
  ],

  guidesSidebar: [
    {
      type: 'doc',
      id: 'guides/index',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'Development',
      items: [{ type: 'autogenerated', dirName: 'guides/development' }],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [{ type: 'autogenerated', dirName: 'guides/deployment' }],
    },
  ],
};

export default sidebars;
